# Generated by Django 2.1.5 on 2020-08-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_page_last_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='comment',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
